backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "english-content"
    label: "English Content"
    files:
      - name: "english-homepage"
        label: "Homepage (English)"
        file: "content/site-content.json"
        fields:
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Company Name", name: "tagline", widget: "string"}
              - {label: "Subtitle", name: "subtitle", widget: "string"}
              - {label: "Main Title", name: "title", widget: "string"}
              - {label: "Scroll Text", name: "scrollText", widget: "string"}
              - {label: "Portrait Image", name: "portraitImage", widget: "image", required: false}
          
          - label: "Services Section"
            name: "services"
            widget: "object"
            fields:
              - {label: "Section Label", name: "sectionLabel", widget: "string"}
              - {label: "Section Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - label: "Service Cards"
                name: "cards"
                widget: "list"
                fields:
                  - {label: "Icon", name: "icon", widget: "string"}
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Description", name: "description", widget: "text"}
          
          - label: "Case Studies"
            name: "caseStudies"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Won Cases", name: "wonCases", widget: "string"}
              - {label: "Years Range", name: "yearsRange", widget: "string"}
          
          - label: "Testimonial"
            name: "testimonial"
            widget: "object"
            fields:
              - {label: "Quote", name: "quote", widget: "text"}
              - {label: "Attribution", name: "attribution", widget: "string"}
          
          - label: "Team Section"
            name: "team"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - label: "Team Members"
                name: "members"
                widget: "list"
                fields:
                  - {label: "Name", name: "name", widget: "string"}
                  - {label: "Bio", name: "bio", widget: "text"}
                  - {label: "Photo", name: "photo", widget: "image", required: false}
          
          - label: "Contact Information"
            name: "contact"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Office", name: "office", widget: "string"}
              - {label: "Phone", name: "phone", widget: "string"}
              - {label: "Email", name: "email", widget: "string"}
              - {label: "Fax", name: "fax", widget: "string"}
              - {label: "Address", name: "address", widget: "text"}
          
          - label: "Footer"
            name: "footer"
            widget: "object"
            fields:
              - {label: "Copyright", name: "copyright", widget: "string"}
              - {label: "Credit", name: "credit", widget: "string"}

  - name: "russian-content"
    label: "Russian Content"
    files:
      - name: "russian-homepage"
        label: "Homepage (Russian)"
        file: "content/site-content-ru.json"
        fields:
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Company Name", name: "tagline", widget: "string"}
              - {label: "Subtitle", name: "subtitle", widget: "string"}
              - {label: "Main Title", name: "title", widget: "string"}
              - {label: "Scroll Text", name: "scrollText", widget: "string"}
              - {label: "Portrait Image", name: "portraitImage", widget: "image", required: false}
          
          - label: "Services Section"
            name: "services"
            widget: "object"
            fields:
              - {label: "Section Label", name: "sectionLabel", widget: "string"}
              - {label: "Section Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - label: "Service Cards"
                name: "cards"
                widget: "list"
                fields:
                  - {label: "Icon", name: "icon", widget: "string"}
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Description", name: "description", widget: "text"}
          
          - label: "Case Studies"
            name: "caseStudies"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Won Cases", name: "wonCases", widget: "string"}
              - {label: "Years Range", name: "yearsRange", widget: "string"}
          
          - label: "Testimonial"
            name: "testimonial"
            widget: "object"
            fields:
              - {label: "Quote", name: "quote", widget: "text"}
              - {label: "Attribution", name: "attribution", widget: "string"}
          
          - label: "Team Section"
            name: "team"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - label: "Team Members"
                name: "members"
                widget: "list"
                fields:
                  - {label: "Name", name: "name", widget: "string"}
                  - {label: "Bio", name: "bio", widget: "text"}
                  - {label: "Photo", name: "photo", widget: "image", required: false}
          
          - label: "Contact Information"
            name: "contact"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Office", name: "office", widget: "string"}
              - {label: "Phone", name: "phone", widget: "string"}
              - {label: "Email", name: "email", widget: "string"}
              - {label: "Fax", name: "fax", widget: "string"}
              - {label: "Address", name: "address", widget: "text"}
          
          - label: "Footer"
            name: "footer"
            widget: "object"
            fields:
              - {label: "Copyright", name: "copyright", widget: "string"}
              - {label: "Credit", name: "credit", widget: "string"}